from django.urls import path
from . import views

urlpatterns = [
    path('', views.login),
    path('home', views.login),
    path('login', views.login),
    path('logoutu/', views.logoutu),
    path('logouta/', views.logouta),
    path('reg', views.reg),
    path('loginTask/', views.loginTask),
    path('regTask', views.regTask),
    path('desk', views.desk),
    path('insert', views.insert),
    path('insertTask', views.insertTask),
    path('emprec', views.emprec),
    path('custrec', views.custrec),
    path('prorec', views.prorec),
    path('sellrec', views.sellrec),
    path('editcust', views.editcust),
    path('editpro', views.editpro),
    path('editemp', views.editemp),
    path('editTaskemp', views.editTaskemp),
    path('editTaskcust', views.editTaskcust),
    path('editTaskpro', views.editTaskpro),
    path('deletetaskpro', views.deletetaskpro),
    path('deletetaskcust', views.deletetaskcust),
    path('deletetaskemp', views.deletetaskemp),
    path('proddetail', views.proddetail),
    path('cart', views.cart),
    path('carttask', views.carttask),
    path('buy', views.buy),
    path('buynow', views.buynow),
    path('desk', views.desk),
    path('soldprod', views.soldprod),
    path('myorder', views.myorder),
    path('userprofile', views.userprofile),
    path('adminprofile', views.adminprofile),
    path('invoice', views.invoice) 
]
